language : node_js
node_js :
 - stable
install:
 - npm install
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run test:osx          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run test:lin        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "win" ]]; then npm run test:win          ; fi
