language : node_js
node_js :
 - stable
install:
 - npm install
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; npm test:linux; fi
  - elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; npm test:osx; fi
  - elif [[ "$TRAVIS_OS_NAME" == "win" ]]; npm test:win; fi